### ISSUE TITLE
ActivityBar doesn't dismiss when called straight after 'showWithStatus'

### ISSUE THREAD

**Issue by adamransom** [zacaltman/ZAActivityBar#1]
If you call `showWithStatus` and then call `dismiss` in quick succession after, the dismiss animation won't play and the ActivityBar will get stuck on the screen.

I could look into this if I have time, but just letting you know.

**Comment by zacaltman** [comment]
I'll check it out tonight.

**Comment by zacaltman** [comment]
Fixed.
