### ISSUE TITLE
Option to put the ZAActivityBar in the center of the screen

### ISSUE THREAD

**Issue by codemonkey301** [zacaltman/ZAActivityBar#17]
I think ZAActivityBar is awesome but I am having hard time using it because it blocks the bottom portion of the app where other information like iAd is displayed.

Have you consider putting in the cetner as an option?

Just an enhancement suggestion.

Thanks,

**Comment by zacaltman** [comment]
I suggest using SVProgressHUD or MBProgressHUD as an alternative or setLocationTabBar to bump the bar above your ads.

**Comment by codemonkey301** [comment]
Thank you. I will look into that

On Apr 15, 2013, at 8:58 PM, Zac Altman notifications@github.com wrote:

I suggest using SVProgressHUD or MBProgressHUD as an alternative or setLocationTabBar to bump the bar above your ads.

\
