### ISSUE TITLE
Feature request: set bottom position of activity bar

### ISSUE THREAD

**Issue by chrisben** [zacaltman/ZAActivityBar#3]
Hi there, first of all thanks for this control, it is very useful.

I would like to be able to define the position where the activity bar appears: I would like to be able to set it above my tab bar (so that it doesn't prevent people from interacting with the tab bar while it's displayed).
This would ideally be a method to set the height between the bottom of the screen and the bottom of the activity bar, or else a define like those in the header file.

I suppose I could just set a new frame to this customised uiview, but it would be cool and perhaps safer to be able to set it using a control's own method (to avoid problems with slide out animation for instance).

**Comment by zacaltman** [comment]
Temporary fix for now. Change the BOTTOM_OFFSET value in the header.

**Comment by chrisben** [comment]
Thanks, that will do for now.

**Comment by ghost** [comment]
I just contributed a way to change the location at https://github.com/darrenmartz/ZAActivityBar

[ZAActivityBar setLocationBottom];
[ZAActivityBar setLocationStausBar];
[ZAActivityBar setLocationNavBar];
