### ISSUE TITLE
Feature request: update text in activity bar

### ISSUE THREAD

**Issue by chrisben** [zacaltman/ZAActivityBar#4]
Is there a way to update the text in the current activity bar?

My use case is a simple progress display with percentage value:

```
Uploading... [17%]
```

that needs to be updated several times until the current operation is complete.
I tried calling showWithStatus on every progress update but -- may be due to issue #1 -- the text in the bar wasn't updated.

I would like that text to be updated without seeing the dismiss animation of the activity bar every time, so maybe there needs to be a updateStatus method for that very purpose.

Cheers.

**Comment by zacaltman** [comment]
Try the latest version. The original code should have supported updates - I was doing it, but not at such a high frequencies, which is where it likely broke down for you. I've improved / fixed the way the bar is animated onto screen, so give that a go.

I just tested the latest code and it works swimmingly for what you want. Here's a video (calls showWithStatus every 0.01 seconds): https://www.dropbox.com/s/0b9h8cfrcfgtweo/ZAActivityBarFastUpdating.mov

Please let me know if it's still playing up for you

**Comment by chrisben** [comment]
That looks pretty good, I'll give it a go then.

Closing this issue.
