### ISSUE TITLE
Feature request: several activity bars at once

### ISSUE THREAD

**Issue by chrisben** [zacaltman/ZAActivityBar#5]
The last feature for me that would make this already great control complete: add the ability to show several activity notifications at once.
When an operation is running and another one is being added concurrently, it would be cool to be able to display that extra operation.

One way would be to stack activity bars (but then there would be a limit to 2 or 3 so that it doesn't fill the whole screen) like those notifications in android 4.

Another way would be to display a default text in the bar (like "2 operations running..."), maybe with a badge with that number on the right,  and with a tap on it you can expand that view to see the details of the running operations (in smaller font size).

To make this work you'd have to change the interface of your class that now relies on a singleton object.
I like how simple and clean it is to use now and don't want to see it getting too complicated.
I suggest those small changes:
- showWithStatus would return a bar id (pointer or number) -- this can be ignored if people don't want to use it
- all existing methods would also be able to take an optional extra parameter : that id -- methods with a single parameter would still remain unchanged
- possibly an extra method or some defines to configure the behaviour/appearance of the stack/number.

**Comment by zacaltman** [comment]
I was actually wondering if i should mention my future plans for this. One of my major pain points is exactly what you're talking about. Often times i run several async functions that i want to keep the user notified of, but... there's no way to stack messages. If one task finishes early... the bar dismisses.

I know there are many ways people want this to perform. I know exactly how i'd implement it class-side:
`[ZAActivityBar showWithStatus:@"Task 1" forId:1];`
`[ZAActivityBar dismissForId:1];`
-- or --
`[ZAActivityBar showWithStatus:@"Task 1" dismissForAction:@"uploadUserData"];`
`[ZAActivityBar dismissForAction:@"uploadUserData"];`

`[ZAActivityBar dismissAll];`

Everything you do for that id is contained (so you could update the status). The current methods would remain for basic use.

_However... visually it's more tricky._

I'm very much on the side of only showing **one message at a time**, it's meant to be non-intrusive in that respect. Secondly, there's the matter of displaying the info on the one bar.

Here's what I have in mind:
• First in first serve - If you send through multiple 'show' messages with different ids, it would show the first message exclusively until it's dismissed. If there are others, it will move down the queue. If other 'show' messages for a different id is sent whilst the bar is on-screen, they wont show. If they're dismissed before the first activity is dismissed, the user will never know what the activity was (just maybe that there were 2 activities, and one was completed).
• Activity count - Show an indicator on the right of how many activities are active.

What are your thoughts on that approach?

**Comment by chrisben** [comment]
First in first serve could be it, just sometimes you want to give a more important status to some notifications, so maybe it would require an extra parameter for priority. There could be 2 levels of priority (normal/high) or a more granular approach like what's used in log files: Info/Warning/Error/Fatal ..
The highest priority would have to be shown first. Notifications with the same priority would be shown first in first serve.

That would require an extra parameter like so:-

```
[ZAActivityBar showWithStatus:@"Task 1" forId:1 withLevel:3];
```

One problem with showing only one activity at a time is that the succes/error notifications would not be shown, or they would be hiding the current operation..
A second problem if we manage to show both at once is how to tell that the succes/error notification is linked to what operation unless the user sets a self-explainable status like "File a.mov successfully sent!".

A separate thought: could notifications alternatively be displayed in the top status bar like push notifications?

**Comment by zacaltman** [comment]
I've done a basic queue system - really needed it in my project asap. Have a go - the demo gives an... okay idea of how it works.

Here's a video: [ZAActivityBar Queuing](https://www.dropbox.com/s/g1ka7j90z81jgjr/ZAActivityBarQueue.mov)
